# Generated by Django 3.0.1 on 2020-03-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarintine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Medical Leave', 'Medical Leave'), ('Full Duty', 'Full Duty')], max_length=30)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
