# Generated by Django 3.0.1 on 2020-03-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarintine',
            name='full_duty',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarintine',
            name='last_bhs',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarintine',
            name='next_bhs',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarintine',
            name='shield',
            field=models.IntegerField(default=20200330),
            preserve_default=False,
        ),
    ]
