# Generated by Django 3.0.1 on 2020-03-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200330_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarintine',
            name='rank',
            field=models.CharField(choices=[('EMT', 'EMT'), ('Medic', 'Medic'), ('Lt', 'Lt'), ('Capt', 'Capt')], default=2, max_length=6),
            preserve_default=False,
        ),
    ]
