# Generated by Django 3.0.1 on 2020-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_quarintine_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('rank', models.CharField(choices=[('EMT', 'EMT'), ('Medic', 'Medic'), ('Lt', 'Lt'), ('Capt', 'Capt')], max_length=6)),
                ('shield', models.IntegerField()),
                ('tour', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2)),
                ('platoon', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2)),
                ('unit', models.CharField(choices=[('33W', '33W'), ('33A', '33A'), ('43V', '43V'), ('43H', '43H'), ('33D', '33D'), ('43G', '43G'), ('33Z', '33Z'), ('43A', '43A'), ('33F', '33F'), ('43C', '43C'), ('33C', '33C'), ('43D', '43D'), ('C43', 'C43'), ('B43', 'B43')], max_length=3)),
                ('status', models.CharField(choices=[('Medical Leave', 'Medical Leave'), ('Full Duty', 'Full Duty'), ('Light Duty', 'Light Duty'), ('Military Leave', 'Military Leave')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='quarintine',
            name='status',
            field=models.CharField(choices=[('Medical Leave', 'Medical Leave'), ('Full Duty', 'Full Duty'), ('Light Duty', 'Light Duty'), ('Military Leave', 'Military Leave')], max_length=30),
        ),
    ]
