# Generated by Django 3.0.1 on 2020-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200331_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='macexp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stateexp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='statenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
