# Generated by Django 3.0.1 on 2020-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20200404_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarintine',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
