# Generated by Django 3.0.1 on 2020-04-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20200404_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarintine',
            name='shield',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
