# Generated by Django 3.0.3 on 2020-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20200422_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cert',
            field=models.CharField(blank=True, choices=[('EMT', 'EMT'), ('Paramedic', 'Paramedic')], max_length=20, null=True),
        ),
    ]
