# Generated by Django 3.0.3 on 2020-05-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_profile_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.CharField(choices=[('33W', '33W'), ('33A', '33A'), ('43V', '43V'), ('43H', '43H'), ('33D', '33D'), ('43G', '43G'), ('33Z', '33Z'), ('43A', '43A'), ('33F', '33F'), ('43C', '43C'), ('33C', '33C'), ('43D', '43D'), ('C43', 'C43'), ('B43', 'B43'), ('VR', 'VR')], max_length=3),
        ),
    ]
