# Generated by Django 3.0.3 on 2020-05-21 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
