# Generated by Django 3.0.3 on 2020-05-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_remove_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='platoon',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('Other', 'Other')], max_length=10),
        ),
    ]
