# Generated by Django 3.0.3 on 2020-10-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20200725_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.CharField(choices=[('33W', '33W'), ('33A', '33A'), ('43V', '43V'), ('43H', '43H'), ('33D', '33D'), ('43G', '43G'), ('33Z', '33Z'), ('43A', '43A'), ('33F', '33F'), ('43C', '43C'), ('33C', '33C'), ('43D', '43D'), ('33E', '33E'), ('C43', 'C43'), ('B43', 'B43'), ('VR', 'VR'), ('Other', 'Other')], max_length=5),
        ),
    ]
